name: Build & Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Cross-Platform Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Get version from Git
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="dev"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "🔖 Version: $VERSION"

      - name: Delete old artifacts
        run: |
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO=${{ github.repository }}
          ARTIFACT_NAME="built-binaries"

          # Get artifact ID
          ARTIFACT_ID=$(gh api repos/$REPO/actions/artifacts --jq ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")

          # Delete artifact if exists
          if [[ -n "$ARTIFACT_ID" ]]; then
            echo "Deleting old artifact: $ARTIFACT_ID"
            gh api --method DELETE repos/$REPO/actions/artifacts/$ARTIFACT_ID
          else
            echo "No previous artifact found."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Run build script
        run: |
          chmod +x scripts/build
          scripts/build "$VERSION"

      - name: Upload latest artifacts (MacOS / arm64)
        uses: actions/upload-artifact@v4
        with:
          name: polarlite-darwin-arm64
          path: ./dist/polarlite-darwin-arm64

      - name: Upload latest artifacts (Linux / arm64)
        uses: actions/upload-artifact@v4
        with:
          name: polarlite-linux-arm64
          path: ./dist/polarlite-linux-arm64

      - name: Upload latest artifacts (Linux / amd64)
        uses: actions/upload-artifact@v4
        with:
          name: polarlite-darwin-amd64
          path: ./dist/polarlite-linux-amd64

      - name: Upload latest artifacts (Windows / amd64)
        uses: actions/upload-artifact@v4
        with:
          name: polarlite-windows-amd64.exe
          path: ./dist/polarlite-windows-amd64.exe

  release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 New release **${{ github.ref_name }}** is now available!
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release File (MacOS / arm64)
        uses: softprops/action-gh-release@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/dist/polarlite-darwin-arm64
          asset_name: polarlite-darwin-arm64
          tag: ${{ github.ref_name }}
          overwrite: true
